# Generated by Django 3.2.8 on 2022-12-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('social_facebook', models.CharField(blank=True, help_text='Please use the following format: https://', max_length=200, null=True)),
                ('social_twitter', models.CharField(blank=True, help_text='Please use the following format: https://', max_length=200, null=True)),
                ('social_youtube', models.CharField(blank=True, help_text='Please use the following format: https://', max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('social_website', models.CharField(blank=True, help_text='Please use the following format: https://', max_length=200, null=True)),
                ('open_time', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('closed_time', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('publish', models.BooleanField(default=0)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('percentage', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('check', models.BooleanField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=2000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=2000, null=True)),
                ('note', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('select_opt', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=None, max_length=60, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewprofile',
            fields=[
                ('value', models.CharField(choices=[('up', 'up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('votee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('voting', models.ManyToManyField(blank=True, related_name='profile_likes', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('pin_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('recipient', models.ManyToManyField(blank=True, related_name='messages', to='users.Profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
