# Generated by Django 3.2.8 on 2022-02-19 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created', '-count']},
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 2, 19), null=True),
        ),
    ]
