# Generated by Django 3.2.8 on 2022-02-19 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220219_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 19, 26, 55, 654337, tzinfo=utc), null=True),
        ),
    ]
