# Generated by Django 3.2.8 on 2022-02-20 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 10, 31, 48, 782357, tzinfo=utc), null=True),
        ),
    ]
